name: docker-build-check

on:
  pull_request:
    branches: ['main']
    paths:
      - build/docker/**

jobs:
  docker-build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Try to build docker image
        run: | 
          docker build -f build/docker/Dockerfile -t wintry:latest .
