name: docker-push

on:
  pull_request:
    branches: ['main']

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Gather poetry dynamic version
        id: poetry-version
        run: >-
          pip install poetry poetry-dynamic-versioning
          poetry install

          echo "::set-output name=VERSION::$(
            poetry version | 
            awk '{print $2}' | 
            awk -F'.' '{print $1"."$2"."$3}'
          )"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: build/docker/Dockerfile
          tags: d33bs/wintry:latest,d33bs/wintry:${{ steps.poetry-version.outputs.VERSION }}
